# Blog settings
permalink: /blog/:title


# My variables
name: Dispatches/أيفادات
eng-name: Dispatches
ara-name: إيفادات
description: Personal blog about XR and other things. I write in English, Arabic, C#, C++.


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]


plugins:
  - jekyll-seo-tag
  - jekyll-sitemap


# Sass
sass:
  style: :compressed
  sass_dir: _sass


# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge

# SEO
twitter:
  username: stenfeio
  card: summary
google_site_verification: vX7R4Cr4bb8x2WaAIhC_J1IMf_fyn3AsjqH1RST0N08
