# Blog settings
permalink: /blog/:title


# My variables
name: Dispatches/أيفادات
eng-name: Dispatches
ara-name: إيفادات
description: Personal blog about VR and CS education and other things. I write in English, Arabic, C#, C++.
google_verification: null


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]


# Sass
sass:
  style: :compressed
  sass_dir: _sass


# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
