# Blog settings
permalink: /blog/:title


# My variables
name: Dispatches/أيفادات
eng-name: Dispatches
ara-name: إيفادات
description: Talal Alothman. Talking about VR AR XR Spatial User Interfaces!
author: Talal Alothman

# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]


plugins:
  - jekyll-seo-tag
  - jekyll-sitemap


# Sass
sass:
  style: :compressed
  sass_dir: _sass


# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge

# SEO
twitter:
  username: talalhalothman
  card: summary
google_site_verification: vX7R4Cr4bb8x2WaAIhC_J1IMf_fyn3AsjqH1RST0N08

# Sitemap
url: https://talothman.github.io

# Collections
collections:
  projects:
    output: true